---

- name: Install which (CentOS, RHEL)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - which
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
